/**
 * Sidemenu Options for Admin
 */
export const SideBarAdminMenu = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'assets/Sidenav-Icons/dashboard.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/dashboard.png',
    url: 'dashboard',
    svgIcon: '',
  },
  {
    id: '2',
    title: 'Screenshots',
    icon: 'assets/Sidenav-Icons/screenshots.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/screenshots.png',
    url: 'screenshots',
    svgIcon: '',
  },
  {
    id: '3',
    title: 'RealTime',
    icon: 'assets/Sidenav-Icons/realtime.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/realtime.png',
    url: 'realtime',
    svgIcon: ''
  },
  {
    id: '4',
    title: 'Organization',
    icon: 'assets/Sidenav-Icons/organization.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/organization.png',
    url: 'organization/organization-setup/organization-profile',
    svgIcon: '',
  },
  {
    id: '5',
    title: 'Manage',
    icon: 'assets/Sidenav-Icons/manage.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/manage.png',
    url: 'manage',
    svgIcon: '',
  },
  {
    id: '6',
    title: 'Calendar',
    icon: 'assets/Sidenav-Icons/calendar.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/calendar.png',
    url: 'calendar/admin',
    svgIcon: 'calendar',
  },
  {
    id: '7',
    title: 'Attendance',
    icon: 'assets/Sidenav-Icons/attendance.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/attendance.png',
    url: 'attendance/settings/general-settings',
    svgIcon: '',
  },
  {
    id: '8',
    title: 'Timesheets',
    icon: 'assets/Sidenav-Icons/timesheet.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/timesheet.png',
    url: 'timesheets/admin',
    svgIcon: 'timesheet',
  },
  {
    id: '9',
    title: 'Leave',
    icon: 'assets/Sidenav-Icons/leave.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/leave.png',
    url: 'leave/settings/general-setting',
    svgIcon: 'leave',
  },
  {
    id: '10',
    title: 'Expenses',
    icon: 'assets/Sidenav-Icons/expenses.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/expenses.png',
    url: 'expense',
    svgIcon: 'expenses',
  },
  {
    id: '11',
    title: 'Alerts',
    icon: 'assets/Sidenav-Icons/alert.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/alerts.png',
    url: 'alerts',
    svgIcon: 'alert',
  },
  {
    id: '12',
    title: 'Payroll',
    icon: 'assets/Sidenav-Icons/payroll.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/payroll.png',
    url: 'payroll/settings/general-settings',
    svgIcon: 'payroll',
  },
  {
    id: '13',
    title: 'Taxation',
    icon: 'assets/Sidenav-Icons/taxation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/taxation.png',
    url: 'taxation/sections',
    svgIcon: 'taxation',
  },
  {
    id: '14',
    title: 'Reports',
    icon: 'assets/Sidenav-Icons/reports.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/reports.png',
    url: 'reports',
    svgIcon: 'reports',
  },
  {
    id: '15',
    title: 'Separation',
    icon: 'assets/Sidenav-Icons/separation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/separation.png',
    url: 'separation',
    svgIcon: '',
  },
  {
    id: '16',
    title: 'Settings',
    icon: 'assets/Sidenav-Icons/settings.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/settings.png',
    url: 'settings',
    svgIcon: 'settings',
  },
  {
    id: '17',
    icon: 'assets/Sidenav-Icons/permission.png',
    title: 'Permissions',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/permission.png',
    url: 'permissions',
    svgIcon: '',
  },
  {
    id: '17',
    icon: 'assets/Sidenav-Icons/roles.png',
    title: 'Roles',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/roles.png',
    url: 'roles',
    svgIcon: '',
  },
  {
    id: '18',
    icon: 'assets/Sidenav-Icons/rolePermission.png',
    title: 'Role Permission',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/rolePermission.png',
    url: 'role-permission',
    svgIcon: '',
  },
  {
    id: '19',
    icon: 'assets/Sidenav-Icons/approvals.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/approval.png',
    title: 'Approvals',
    url: 'approvals',
    svgIcon: '',
  },
  {
    id: '20',
    title: 'Interview Process',
    icon: 'assets/Sidenav-Icons/settings.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/settings.png',
    url: 'interview-process',
    svgIcon: '',
  },
  {
    id: '22',
    title: 'Feedback',
    icon: 'assets/Sidenav-Icons/feedback.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/feedback.png',    
    url: 'feedback',
    svgIcon: '',
  },
  {
    id: '23',
    title: 'Helpdesk',
    icon: 'assets/Sidenav-Icons/helpdesk.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/helpdesk.png',    
    url: 'helpdesk',
    svgIcon: '',
  }  
];

/**
 * Sidemenu Options for User
 */
export const SideBarUserMenu = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'assets/Sidenav-Icons/dashboard.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/dashboard.png',
    url: 'dashboard/user',
    svgIcon: '',
  },
  {
    id: '2',
    title: 'Screenshots',
    icon: 'assets/Sidenav-Icons/screenshots.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/screenshots.png',
    url: 'screenshots',
    svgIcon: '',
  },
  {
    id: '3',
    title: 'RealTime',
    icon: 'assets/Sidenav-Icons/realtime.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/realtime.png',
    url: 'realtime',
    svgIcon: '',
  },

  {
    id: '17',
    title: 'Tasks',
    icon: 'assets/Sidenav-Icons/tasks.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/tasks.png',
    url: 'tasks',
    svgIcon: '',
  },

  {
    id: '4',
    title: 'Alerts',
    icon: 'assets/Sidenav-Icons/alert.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/alerts.png',
    svgIcon: 'alert',
  },
  {
    id: '5',
    title: 'Organization',
    icon: 'assets/Sidenav-Icons/organization.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/organization.png',
    url: 'organization/company-policies',
    svgIcon: '',
  },
  {
    id: '6',
    title: 'Calendar',
    icon: 'assets/Sidenav-Icons/calendar.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/calendar.png',
    url: 'calendar/user',
    svgIcon: 'calendar',
  },
  {
    id: '7',
    title: 'Leave',
    icon: 'assets/Sidenav-Icons/leave.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/leave.png',
    url: 'leave/my-application',
    svgIcon: 'leave',
  },
  {
    id: '8',
    title: 'Attendance',
    icon: 'assets/Sidenav-Icons/attendance.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/attendance.png',
    url: 'attendance/my-attendance-records',
    svgIcon: '',
  },
  {
    id: '9',
    title: 'Timesheets',
    icon: 'assets/Sidenav-Icons/timesheet.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/timesheet.png',
    url: 'timesheets/user',
    svgIcon: 'timesheet',
  },
  {
    id: '10',
    title: 'Taxation',
    icon: 'assets/Sidenav-Icons/taxation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/taxation.png',
    url: 'taxation/tax-declaration',
    svgIcon: 'taxation',
  },
  {
    id: '11',
    title: 'Expenses',
    icon: 'assets/Sidenav-Icons/expenses.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/expenses.png',
    url: 'expense/my-expense',
    svgIcon: 'expenses',
  },
  {
    id: '12',
    title: 'PaySlips',
    icon: 'assets/Sidenav-Icons/payslip.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/payslip.png',
    svgIcon: '',
  },
  {
    id: '13',
    title: 'Separation',
    icon: 'assets/Sidenav-Icons/separation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/separation.png',
    url: 'separation',
    svgIcon: '',
  },
  {
    id: '14',
    title: 'Reports',
    icon: 'assets/Sidenav-Icons/reports.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/reports.png',
    url: 'reports',
    svgIcon: 'reports',
  },
  {
    id: '15',
    title: 'Manual Time',
    icon: 'assets/Sidenav-Icons/manualTime.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/manualTime.png',
    url: 'manual-time',
    svgIcon: 'time',
  },
  {
    id: '16',
    title: 'Settings',
    icon: 'assets/Sidenav-Icons/settings.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/settings.png',
    url: 'settings/user-preferences',
    svgIcon: 'settings',
  },
  {
    id: '17',
    title: 'Helpdesk',
    icon: 'assets/Sidenav-Icons/helpdesk.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/helpdesk.png',    
    url: 'helpdesk',
    svgIcon: '',
  }
];
