/**
 * Sidemenu Options for Admin
 */
export const SideBarAdminMenu = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'assets/Sidenav-Icons/dashboard.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/dashboard.png',
    url: 'dashboard',
  },
  {
    id: '2',
    title: 'Screenshots',
    icon: 'assets/Sidenav-Icons/screenshots.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/screenshots.png',
    url: 'screenshots',
  },
  // {
  //   id: '19',
  //   icon: 'assets/Sidenav-Icons/livescreen.png',
  //   lightIcon: 'assets/Sidenav-Icons/light-Icons/liveScreen.png',
  //   title: 'View Live Screen',
  //   url: 'viewLiveScreen'
  // },
  {
    id: '3',
    title: 'RealTime',
    icon: 'assets/Sidenav-Icons/realtime.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/realtime.png',
    url: 'realtime',
  },
  {
    id: '4',
    title: 'Organization',
    icon: 'assets/Sidenav-Icons/organization.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/organization.png',
    url: 'organization',
  },
  {
    id: '5',
    title: 'Manage',
    icon: 'assets/Sidenav-Icons/manage.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/manage.png',
    url: 'manage',
  },
  {
    id: '6',
    title: 'Calendar',
    icon: 'assets/Sidenav-Icons/calendar.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/calendar.png',
    url: 'calendar/admin',
  },
  {
    id: '7',
    title: 'Attendance',
    icon: 'assets/Sidenav-Icons/attendance.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/attendance.png',
    url: 'attendance',
  },
  {
    id: '8',
    title: 'Timesheets',
    icon: 'assets/Sidenav-Icons/timesheet.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/timesheet.png',
    url: 'timesheets/admin',
  },
  {
    id: '9',
    title: 'Leave',
    icon: 'assets/Sidenav-Icons/leave.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/leave.png',
    url: 'leave',
  },
  {
    id: '10',
    title: 'Expenses',
    icon: 'assets/Sidenav-Icons/expenses.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/expenses.png',
    url: 'expense',
  },
  {
    id: '11',
    title: 'Alerts',
    icon: 'assets/Sidenav-Icons/alert.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/alerts.png',
    url: 'alerts',
  },
  {
    id: '12',
    title: 'Payroll',
    icon: 'assets/Sidenav-Icons/payroll.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/payroll.png',
    url: 'payroll',
  },
  {
    id: '13',
    title: 'Taxation',
    icon: 'assets/Sidenav-Icons/taxation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/taxation.png',
    url: 'taxation',
  },
  {
    id: '14',
    title: 'Reports',
    icon: 'assets/Sidenav-Icons/reports.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/reports.png',
    url: 'reports',
  },
  {
    id: '15',
    title: 'Separation',
    icon: 'assets/Sidenav-Icons/separation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/separation.png',
    url: 'separation',
  },
  {
    id: '16',
    title: 'Settings',
    icon: 'assets/Sidenav-Icons/settings.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/settings.png',
    url: 'settings',
  },
  {
    id: '17',
    icon: 'assets/Sidenav-Icons/permission.png',
    title: 'Permissions',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/permission.png',
    url: 'permissions',
  },
  {
    id: '17',
    icon: 'assets/Sidenav-Icons/roles.png',
    title: 'Roles',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/roles.png',
    url: 'roles',
  },
  {
    id: '18',
    icon: 'assets/Sidenav-Icons/rolePermission.png',
    title: 'Role Permission',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/rolePermission.png',
    url: 'role-permission',
  },
  {
    id: '19',
    icon: 'assets/Sidenav-Icons/approvals.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/approval.png',
    title: 'Approvals',
    url: 'approvals',
  },
  {
    id: '20',
    title: 'Interview Process',
    icon: 'assets/Sidenav-Icons/settings.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/settings.png',
    url: 'interview-process',
  },
  {
    id: '21',
    title: 'Subscriptions',
    icon: 'assets/Sidenav-Icons/expenses.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/expenses.png',
    url: 'subscription/plans',
  },
  {
    id: '22',
    title: 'Feedback Form',
    icon: 'assets/Sidenav-Icons/feedback.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/feedback.png',    
    url: 'feedback-form',
  },
];

/**
 * Sidemenu Options for User
 */
export const SideBarUserMenu = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'assets/Sidenav-Icons/dashboard.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/dashboard.png',
    url: 'dashboard/user',
  },
  {
    id: '2',
    title: 'Screenshots',
    icon: 'assets/Sidenav-Icons/screenshots.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/screenshots.png',
    url: 'screenshots',
  },
  // {
  //   id: '17',
  //   title: 'View Live Screen',
  //   icon: 'assets/Sidenav-Icons/livescreen.png',
  //   lightIcon: 'assets/Sidenav-Icons/light-Icons/liveScreen.png',
  //   url: 'viewLiveScreen'
  // },
  {
    id: '3',
    title: 'RealTime',
    icon: 'assets/Sidenav-Icons/realtime.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/realtime.png',
    url: 'realtime',
  },

  {
    id: '17',
    title: 'Tasks',
    icon: 'assets/Sidenav-Icons/tasks.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/tasks.png',
    url: 'tasks',
  },

  {
    id: '4',
    title: 'Alerts',
    icon: 'assets/Sidenav-Icons/alert.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/alerts.png',
  },
  {
    id: '5',
    title: 'Organization',
    icon: 'assets/Sidenav-Icons/organization.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/organization.png',
    url: 'organization',
  },
  {
    id: '6',
    title: 'Calendar',
    icon: 'assets/Sidenav-Icons/calendar.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/calendar.png',
    url: 'calendar/user',
  },
  {
    id: '7',
    title: 'Leave',
    icon: 'assets/Sidenav-Icons/leave.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/leave.png',
    url: 'leave',
  },
  {
    id: '8',
    title: 'Attendance',
    icon: 'assets/Sidenav-Icons/attendance.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/attendance.png',
    url: 'attendance',
  },
  {
    id: '9',
    title: 'Timesheets',
    icon: 'assets/Sidenav-Icons/timesheet.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/timesheet.png',
    url: 'timesheets/user',
  },
  {
    id: '10',
    title: 'Taxation',
    icon: 'assets/Sidenav-Icons/taxation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/taxation.png',
    url: 'taxation/tax-declaration',
  },
  {
    id: '11',
    title: 'Expenses',
    icon: 'assets/Sidenav-Icons/expenses.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/expenses.png',
    url: 'expense',
  },
  {
    id: '12',
    title: 'PaySlips',
    icon: 'assets/Sidenav-Icons/payslip.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/payslip.png',
  },
  {
    id: '13',
    title: 'Separation',
    icon: 'assets/Sidenav-Icons/separation.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/separation.png',
    url: 'separation',
  },
  {
    id: '14',
    title: 'Reports',
    icon: 'assets/Sidenav-Icons/reports.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/reports.png',
    url: 'reports',
  },
  {
    id: '15',
    title: 'Manual Time',
    icon: 'assets/Sidenav-Icons/manualTime.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/manualTime.png',
    url: 'manual-time',
  },
  {
    id: '16',
    title: 'Settings',
    icon: 'assets/Sidenav-Icons/settings.png',
    lightIcon: 'assets/Sidenav-Icons/light-Icons/settings.png',
    url: 'settings/user-preferences',
  },
];
